spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://127.0.0.1:9000 #{uri del server}
      client:
        registration:
          courses:
            provider: spring
            client-id: courses
            client-secret: 1234
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8082/courses/authorized
            scope: read
            client-name: courses
        provider:
          spring:
            issuer-uri: http://127.0.0.1:9000 #{uri del server}